name: build games
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - games/**
  schedule:
    - cron: "0 0 * * 1"

permissions:
  contents: read
  packages: write

jobs:
  pushAMD64:
    name: "games_AMD64:${{ matrix.game }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        game:
          - samp-wine

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./games/${{ matrix.game }}
          file: ./games/${{ matrix.game }}/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ghcr.io/${{ github.repository }}/games:${{ matrix.game }}
